exports = module.exports = {
	mxa310: {
		id: 'mxa310',
		family: 'mxa',
		type: 'mixer',
		label: 'MXA310 Table Array Microphone',
		channels: {
			1: {
				id: '1',
				label: 'Microphone 1',
				type: 'input',
				port: 'mic',
				peq: 4,
				automix: true,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			2: {
				id: '2',
				label: 'Microphone 2',
				type: 'input',
				port: 'mic',
				peq: 4,
				automix: true,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			3: {
				id: '3',
				label: 'Microphone 3',
				type: 'input',
				port: 'mic',
				peq: 4,
				automix: true,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			4: {
				id: '4',
				label: 'Microphone 4',
				type: 'input',
				port: 'mic',
				peq: 4,
				automix: true,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			5: {
				id: '5',
				label: 'Automixer Output',
				type: 'automix',
				port: 'automix',
				peq: 4,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
		},
	},
	mxa910: {
		id: 'mxa910',
		family: 'mxa',
		type: 'mixer',
		label: 'MXA910 Ceiling Array Microphone',
		channels: {
			1: {
				id: '1',
				label: 'Microphone 1',
				type: 'input',
				port: 'mic',
				peq: 4,
				automix: true,
				aec: false,
				nr: false,
				agc: true,
				comp: false,
				delay: false,
			},
			2: {
				id: '2',
				label: 'Microphone 2',
				type: 'input',
				port: 'mic',
				peq: 4,
				automix: true,
				aec: false,
				nr: false,
				agc: true,
				comp: false,
				delay: false,
			},
			3: {
				id: '3',
				label: 'Microphone 3',
				type: 'input',
				port: 'mic',
				peq: 4,
				automix: true,
				aec: false,
				nr: false,
				agc: true,
				comp: false,
				delay: false,
			},
			4: {
				id: '4',
				label: 'Microphone 4',
				type: 'input',
				port: 'mic',
				peq: 4,
				automix: true,
				aec: false,
				nr: false,
				agc: true,
				comp: false,
				delay: false,
			},
			5: {
				id: '5',
				label: 'Microphone 5',
				type: 'input',
				port: 'mic',
				peq: 4,
				automix: true,
				aec: false,
				nr: false,
				agc: true,
				comp: false,
				delay: false,
			},
			6: {
				id: '6',
				label: 'Microphone 6',
				type: 'input',
				port: 'mic',
				peq: 4,
				automix: true,
				aec: false,
				nr: false,
				agc: true,
				comp: false,
				delay: false,
			},
			7: {
				id: '7',
				label: 'Microphone 7',
				type: 'input',
				port: 'mic',
				peq: 4,
				automix: true,
				aec: false,
				nr: false,
				agc: true,
				comp: false,
				delay: false,
			},
			8: {
				id: '8',
				label: 'Microphone 8',
				type: 'input',
				port: 'mic',
				peq: 4,
				automix: true,
				aec: false,
				nr: false,
				agc: true,
				comp: false,
				delay: false,
			},
			9: {
				id: '9',
				label: 'Automixer Output',
				type: 'automix',
				port: 'automix',
				peq: 4,
				automix: false,
				aec: true,
				nr: false,
				agc: false,
				comp: true,
				delay: true,
			},
		},
	},
	p300: {
		id: 'p300',
		family: 'imx',
		label: 'IntelliMix P300 Processor',
		type: 'matrix',
		channels: {
			1: {
				id: '1',
				label: 'Dante Input 1',
				type: 'input',
				port: 'dante',
				peq: 4,
				automix: true,
				aec: true,
				nr: true,
				agc: true,
				comp: false,
				delay: false,
			},
			2: {
				id: '2',
				label: 'Dante Input 2',
				type: 'input',
				port: 'dante',
				peq: 4,
				automix: true,
				aec: true,
				nr: true,
				agc: true,
				comp: false,
				delay: false,
			},
			3: {
				id: '3',
				label: 'Dante Input 3',
				type: 'input',
				port: 'dante',
				peq: 4,
				automix: true,
				aec: true,
				nr: true,
				agc: true,
				comp: false,
				delay: false,
			},
			4: {
				id: '4',
				label: 'Dante Input 4',
				type: 'input',
				port: 'dante',
				peq: 4,
				automix: true,
				aec: true,
				nr: true,
				agc: true,
				comp: false,
				delay: false,
			},
			5: {
				id: '5',
				label: 'Dante Input 5',
				type: 'input',
				port: 'dante',
				peq: 4,
				automix: true,
				aec: true,
				nr: true,
				agc: true,
				comp: false,
				delay: false,
			},
			6: {
				id: '6',
				label: 'Dante Input 6',
				type: 'input',
				port: 'dante',
				peq: 4,
				automix: true,
				aec: true,
				nr: true,
				agc: true,
				comp: false,
				delay: false,
			},
			7: {
				id: '7',
				label: 'Dante Input 7',
				type: 'input',
				port: 'dante',
				peq: 4,
				automix: true,
				aec: true,
				nr: true,
				agc: true,
				comp: false,
				delay: false,
			},
			8: {
				id: '8',
				label: 'Dante Input 8',
				type: 'input',
				port: 'dante',
				peq: 4,
				automix: true,
				aec: true,
				nr: true,
				agc: true,
				comp: false,
				delay: false,
			},
			9: {
				id: '9',
				label: 'Dante Input 9',
				type: 'input',
				port: 'dante',
				peq: 2,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			10: {
				id: '10',
				label: 'Dante Input 10',
				type: 'input',
				port: 'dante',
				peq: 2,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			11: {
				id: '11',
				label: 'Analog Input 1',
				type: 'input',
				port: 'analog',
				peq: 2,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			12: {
				id: '12',
				label: 'Analog Input 2',
				type: 'input',
				port: 'analog',
				peq: 2,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			13: {
				id: '13',
				label: 'USB Input',
				type: 'input',
				port: 'usb',
				peq: 2,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			14: {
				id: '14',
				label: 'Mobile Input',
				type: 'input',
				port: 'mobile',
				peq: 2,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			15: {
				id: '15',
				label: 'Dante Output 1',
				type: 'output',
				port: 'dante',
				peq: 4,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			16: {
				id: '16',
				label: 'Dante Output 2',
				type: 'output',
				port: 'dante',
				peq: 4,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			17: {
				id: '17',
				label: 'Analog Output 1',
				type: 'output',
				port: 'analog',
				peq: 2,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: true,
			},
			18: {
				id: '18',
				label: 'Analog Output 2',
				type: 'output',
				port: 'analog',
				peq: 2,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: true,
			},
			19: {
				id: '19',
				label: 'USB Output',
				type: 'output',
				port: 'usb',
				peq: 2,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: true,
			},
			20: {
				id: '20',
				label: 'Mobile Output',
				type: 'output',
				port: 'mobile',
				peq: 0,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			21: {
				id: '21',
				label: 'Automixer Output',
				type: 'automix',
				port: 'automix',
				peq: 0,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: true,
				delay: false,
			},
			23: {
				id: '23',
				label: 'Dante Output 3',
				type: 'output',
				port: 'dante',
				peq: 4,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			24: {
				id: '24',
				label: 'Dante Output 4',
				type: 'output',
				port: 'dante',
				peq: 4,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			25: {
				id: '25',
				label: 'Dante Output 5',
				type: 'output',
				port: 'dante',
				peq: 4,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			26: {
				id: '26',
				label: 'Dante Output 6',
				type: 'output',
				port: 'dante',
				peq: 4,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			27: {
				id: '27',
				label: 'Dante Output 7',
				type: 'output',
				port: 'dante',
				peq: 4,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
			28: {
				id: '28',
				label: 'Dante Output 8',
				type: 'output',
				port: 'dante',
				peq: 4,
				automix: false,
				aec: false,
				nr: false,
				agc: false,
				comp: false,
				delay: false,
			},
		},
	},
}